export enum AgentBidStatus {
    PENDING = "PENDING",
    ACCEPTED = "ACCEPTED",
    REJECTED = "REJECTED"
}

export enum ActivityLogAction {
    BID_APPROVED = "BID_APPROVED",
    BID_SUBMITTED = "BID_SUBMITTED",
    BID_UPDATED = "BID_UPDATED",
    BID_REMOVED = "BID_REMOVED",
    REQUEST_CREATED = "REQUEST_CREATED",
    REQUEST_UPDATED = "REQUEST_UPDATED",
    REQUEST_APPROVED = "REQUEST_APPROVED",
    REQUEST_REJECTED = "REQUEST_REJECTED",
    SETTINGS_CHANGE = "SETTINGS_CHANGE"
}
